{
 "title": "Camunda Activity Duration Tracking",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Script Task 1",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(camunda_activity_instance_duration_bucket{activity_id=\"ScriptTask1\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Current Total Flow Node Instance Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "camunda_metric_activity_instance_start"
    }
   ]
  },
  {
   "title": "Active Incidents",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "camunda_open_incidents_count" }
   ]
  },
  {
   "title": "Script Task 2",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(camunda_activity_instance_duration_bucket{activity_id=\"ScriptTask2\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Script Task 3",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(camunda_activity_instance_duration_bucket{activity_id=\"ScripTask3\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}