{
 "title": "Camunda Metrics 1",
 "tags": [ "camunda" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "External Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active External Task Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_active_external_task_count"
      }
     ]
    },
    {
     "title": "Suspended External Task Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_suspended_external_task_count"
      }
     ]
    },
    {
     "title": "Locked External Task Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_locked_external_task_count"
      }
     ]
    },
    {
     "title": "Not-Locked External Task Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_external_tasks_not_locked_count"
      }
     ]
    },
    {
     "title": "External Tasks with No Reties Left",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_external_tasks_with_no_retries_left_count"
      }
     ]
    },
    {
     "title": "External Tasks with Reties Left",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_external_tasks_with_retries_left_count"
      }
     ]
    },
    {
     "title": "Active External Tasks Count with Priority between 0 and 100",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 10, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_external_tasks_with_priority_between_0_and_100"
      }
     ]
    },
    {
     "title": "Active External Tasks Count with Priority <= 50",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_external_tasks_with_priority_lower_than_or_equals_50"
      }
     ]
    },
    {
     "title": "Active External Tasks Count with Priority >= 51",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 7, "x": 7, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_external_tasks_with_priority_higher_than_or_equals_51"
      }
     ]
    }
   ]
  },
  {
   "title": "User Log Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "User Log Operation: Activate",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_Activate"
      }
     ]
    },
    {
     "title": "User Log Operation: Activate Batch",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_ActivateBatch"
      }
     ]
    },
    {
     "title": "User Log Operation: Activate Job",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_ActivateJob"
      }
     ]
    },
    {
     "title": "User Log Operation: Activate Job Definition",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_ActivateJobDefinition"
      }
     ]
    },
    {
     "title": "User Log Operation: Activate Process Definition",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_ActivateProcessDefinition"
      }
     ]
    },
    {
     "title": "User Log Operation: Add Attachment",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_AddAttachment"
      }
     ]
    },
    {
     "title": "User Log Operation: Add Group Link",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_AddGroupLink"
      }
     ]
    },
    {
     "title": "User Log Operation: Add User Link",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_AddUserLink"
      }
     ]
    },
    {
     "title": "User Log Operation: Assign",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_Assign"
      }
     ]
    },
    {
     "title": "User Log Operation: Claim",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_Claim"
      }
     ]
    },
    {
     "title": "User Log Operation: Complete",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_Complete"
      }
     ]
    },
    {
     "title": "User Log Operation: Create",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_Create"
      }
     ]
    },
    {
     "title": "User Log Operation: Delegate",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_Delegate"
      }
     ]
    },
    {
     "title": "User Log Operation: Delete",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_Delete"
      }
     ]
    },
    {
     "title": "User Log Operation: Delete Attachment",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_DeleteAttachment"
      }
     ]
    },
    {
     "title": "User Log Operation: Delete Group Link",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_DeleteGroupLink"
      }
     ]
    },
    {
     "title": "User Log Operation: Delete User Link",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_DeleteUserLink"
      }
     ]
    },
    {
     "title": "User Log Operation: Migrate",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_Migrate"
      }
     ]
    },
    {
     "title": "User Log Operation: Modify Process Instance",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_ModifyProcessInstance"
      }
     ]
    },
    {
     "title": "User Log Operation: Modify Variable",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_ModifyVariable"
      }
     ]
    },
    {
     "title": "User Log Operation: Resolve",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_Resolve"
      }
     ]
    },
    {
     "title": "User Log Operation: Restart Process Instance",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_RestartProcessInstance"
      }
     ]
    },
    {
     "title": "User Log Operation: Set External Task Retries",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_SetExternalTaskRetries"
      }
     ]
    },
    {
     "title": "User Log Operation: Set Job Retries",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_SetJobRetries"
      }
     ]
    },
    {
     "title": "User Log Operation: Set Owner",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_SetOwner"
      }
     ]
    },
    {
     "title": "User Log Operation: Set Priority",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_SetPriority"
      }
     ]
    },
    {
     "title": "User Log Operation: Set Variable",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_SetVariable"
      }
     ]
    },
    {
     "title": "User Log Operation: Suspend",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_Suspend"
      }
     ]
    },
    {
     "title": "User Log Operation: Suspend Batch",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 22 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_SuspendBatch"
      }
     ]
    },
    {
     "title": "User Log Operation: Suspend Job",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 22 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_SuspendJob"
      }
     ]
    },
    {
     "title": "User Log Operation: Suspend Job Definition",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 22 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_SuspendJobDefinition"
      }
     ]
    },
    {
     "title": "User Log Operation: Suspend Process Definition",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 22 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_SuspendProcessDefinition"
      }
     ]
    },
    {
     "title": "User Log Operation: Update",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 25 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_Update"
      }
     ]
    },
    {
     "title": "User Log Operation: Update History Time to Live",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 25 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_user_operation_log_type_UpdateHistoryTimeToLive"
      }
     ]
    }
   ]
  },
  {
   "title": "Timers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Timer Job Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "camunda_active_timer_job_count" }
     ]
    },
    {
     "title": "Suspended Timer Job Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_suspended_timer_job_count"
      }
     ]
    }
   ]
  },
  {
   "title": "Incidents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open Incidents Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "camunda_open_incidents_count" }
     ]
    },
    {
     "title": "Resolved Incidents Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_resolved_incidents_count"
      }
     ]
    },
    {
     "title": "Deleted Incidents Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_deleted_incidents_count"
      }
     ]
    }
   ]
  },
  {
   "title": "Event Subscriptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Message Subscription Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_message_event_subscription_count"
      }
     ]
    },
    {
     "title": "Active Signal Subscription Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_signal_event_subscription_count"
      }
     ]
    },
    {
     "title": "Active Conditional Subscription Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_conditional_event_subscription_count"
      }
     ]
    },
    {
     "title": "Active Compensation Subscription Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_compensation_event_subscription_count"
      }
     ]
    }
   ]
  },
  {
   "title": "User Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active User Tasks",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_active_user_tasks_count"
      }
     ]
    },
    {
     "title": "Suspended User Tasks",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_suspended_user_tasks_count"
      }
     ]
    },
    {
     "title": "Active Unassigned User Tasks Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_active_unassigned_user_tasks_count"
      }
     ]
    }
   ]
  },
  {
   "title": "Identity Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tenant count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_identity_service_tenant_count"
      }
     ]
    },
    {
     "title": "User Count across all Tenants",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_identity_service_user_count"
      }
     ]
    },
    {
     "title": "Group count across all Tenants",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_identity_service_group_count"
      }
     ]
    }
   ]
  },
  {
   "title": "Activity Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Process Instances by Process Definition Key",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_active_process_instance_count",
       "legendFormat": "Key: {{process_definition_key}}"
      }
     ]
    },
    {
     "title": "Activity Instance Start/End Rate per 1min",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(camunda_metric_job_execution_rejected[1m])",
       "legendFormat": "Execution Rejections"
      },
      {
       "expr": "rate(camunda_metric_activity_instance_start[1m])",
       "legendFormat": "Instance Start"
      },
      {
       "expr": "rate(camunda_metric_activity_instance_end[1m])",
       "legendFormat": "Instance End"
      }
     ]
    },
    {
     "title": "Activity Instance Start (Flow Node Instances)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 21 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_metric_activity_instance_start"
      }
     ]
    },
    {
     "title": "Activity Instance End",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 7, "x": 7, "y": 21 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_metric_activity_instance_end"
      }
     ]
    },
    {
     "title": "Job Execution Rejected",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 7, "x": 14, "y": 21 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_metric_job_execution_rejected"
      }
     ]
    }
   ]
  },
  {
   "title": "Job Execution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jobs Successful Executed",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "camunda_metric_job_successful" }
     ]
    },
    {
     "title": "Jobs Locked (Exclusive)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 7, "x": 7, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_metric_job_locked_exclusive"
      }
     ]
    },
    {
     "title": "Jobs Failed to Execute",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 7, "x": 14, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "camunda_metric_job_failed" }
     ]
    }
   ]
  },
  {
   "title": "Job Acquisition",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job Acquisition Attempts",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_metric_job_acquisition_attempt"
      }
     ]
    },
    {
     "title": "Jobs Successfully Acquired",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 7, "x": 7, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_metric_job_acquired_success"
      }
     ]
    },
    {
     "title": "Job Acquire Failure",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 7, "x": 14, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_metric_job_acquired_failure"
      }
     ]
    }
   ]
  },
  {
   "title": "Decision Execution (DMN)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Decision Elements Executed",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "camunda_metric_executed_decision_elements"
      }
     ]
    }
   ]
  }
 ]
}